# Generated by Django 2.2.1 on 2019-07-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeappc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='cover',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cover',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='cover',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Duties',
            field=models.CharField(max_length=1000),
        ),
    ]
