# Generated by Django 2.2.1 on 2019-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeappc', '0003_auto_20190707_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('cover', models.ImageField(default='SOME STRING', upload_to='images/')),
            ],
        ),
    ]
