# Generated by Django 2.2.1 on 2019-07-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeappc', '0007_auto_20190709_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeappc.Education')),
            ],
        ),
    ]
